services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: ft_elk_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elk_es_data:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
    networks:
      - transcendence-prod

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    container_name: ft_elk_kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
    networks:
      - transcendence-prod

  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.2
    container_name: ft_elk_logstash
    volumes:
      - ./infra/elk/logstash/pipeline:/usr/share/logstash/pipeline:ro
    environment:
      - xpack.monitoring.enabled=false
    ports:
      - '5044:5044'
    depends_on:
      - elasticsearch
    networks:
      - transcendence-prod

  filebeat:
    # build:
    #   context: ./infra/elk/filebeat
    #   dockerfile: Dockerfile
    image: docker.elastic.co/beats/filebeat:8.12.2
    container_name: ft_elk_filebeat
    user: root
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run:/var/run:ro
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - filebeat-data:/usr/share/filebeat/data
    command: ['--strict.perms=false']
    depends_on:
      - logstash
    networks:
      - transcendence-prod

volumes:
  elk_es_data:
  filebeat-data:

networks:
  transcendence-prod:
