global:
  scrape_interval: 5s # Check for new data every 5 seconds
  external_labels:
    env: dev
  evaluation_interval: 15s # Check alert rules every 15s

rule_files:
  - 'alert_rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'ft_transcendence_backend'
    static_configs:
      - targets: ['app:3000'] # Connects to the 'app' service on port 3000

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080'] # Even though we map to 8081 externally, use 8080 internally (they are in the same Docker network)
